[ 2023-05-13 10:53:34,112 ] 113 werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[ 2023-05-13 10:53:43,323 ] 1891 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "c:\python\python3.9.1\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python3.9.1\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python3.9.1\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python3.9.1\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python3.9.1\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python3.9.1\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\mlprojects\proj1\app.py", line 18, in index
    return render_template('index.html')
  File "c:\python\python3.9.1\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\python\python3.9.1\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\python\python3.9.1\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python\python3.9.1\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python\python3.9.1\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\python\python3.9.1\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\python\python3.9.1\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2023-05-13 10:53:43,334 ] 113 werkzeug - INFO - 127.0.0.1 - - [13/May/2023 10:53:43] "[35m[1mGET / HTTP/1.1[0m" 500 -
